# app/config/services.yml
services:
    # explicit commands registration
    # see https://stackoverflow.com/a/49136150
    AppBundle\Command\:
        resource: '%kernel.project_dir%/src/AppBundle/Command/*'
        tags: ['console.command']

    cocur_slugify:
        class: Cocur\Slugify\Slugify
        public: true

    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }

    # language-specific layout in 404
    app.language.kernel_request_listener:
        class: AppBundle\EventListener\LanguageListener
        tags:
          - { name: kernel.event_listener, event: kernel.exception, method: setLocale }

    app.twig_extension:
        class: AppBundle\Twig\AppExtension
        arguments: [ "@translator", "@cocur_slugify" ]
        public: false
        tags:
            - { name: twig.extension }
        
    app.imagemagick:
        class:        AppBundle\Utils\ImageMagick\ImageMagickProcessor
        arguments:    [ "%app.imagemagick.processor.arguments%" ]
        public: true
        
    app.xslt_adapter:
        class:        "%app.xslt.adapter.class%"
        arguments:    [ "%app.xslt.adapter.arguments%" ]
    app.xslt:
        class:        AppBundle\Utils\Xsl\XsltProcessor
        calls:
            - [ setAdapter, [ '@app.xslt_adapter' ]]
        public: true

    app.xml_formatter_adapter:
        class:        "%app.xml_formatter.adapter.class%"
        arguments:    [ "%app.xml_formatter.adapter.arguments%" ]
    app.xml_formatter:
        class:        AppBundle\Utils\XmlFormatter\XmlFormatter
        calls:
            - [ setAdapter, [ '@app.xml_formatter_adapter' ]]
        public: true

    app.simplify_geojson:
        class:        AppBundle\Utils\SimplifyGeojsonProcessor
        arguments:    [ "%app.simplify_geojson.processor.arguments%" ]
        public: true

    app.menu_builder:
        class: AppBundle\Menu\Builder
        arguments: [ "@knp_menu.factory", "@translator.default", "@request_stack", "@router"  ]
        tags:
            # The alias is what is used to retrieve the menu
            - { name: knp_menu.menu_builder, method: createTopMenu, alias: top } 
            - { name: knp_menu.menu_builder, method: createMainMenu, alias: main }
            - { name: knp_menu.menu_builder, method: createBreadcrumbMenu, alias: breadcrumb }
            - { name: knp_menu.menu_builder, method: createFooterMainMenu, alias: footer-main }
